from app.models.carrier import Carrier
from app.models.sector import Sector
from app.models.parking_slot import ParkingSlot
from app.models.vehicle import Vehicle
from app.models.vehicle_photo import VehiclePhoto
from app.models.vehicle_event import VehicleEvent
from app.models.vessel import Vessel
from app.models.voyage import Voyage
from app.models.shipment import Shipment